### PR TITLE
Adding new .messages component

### PR DESCRIPTION
**Pull request by ashenden**
See documentation for full overview of component. Analogous to the popular `.alert` component from bootstrap. Supports different states/styles, inverse, and dismissible indicators.

### CODE REVIEW

**Comment by jfurrow** [comment]
Visually this looks great! I'm a little concerned about having to apply the `message-type-style` class to every child. There are a couple of ways I can think of to make this easier:

1. Set the color of children with `.message-{type} > * { color: inherit; }`
2. Remove the `p` selector from the `html, body, p { ... }` declaration and letting paragraphs inherit their color from their parents (this will probably cause issues elsewhere)

What do you think?

**Comment by ashenden** [comment]
@jfurrow yeah, that was something we discussed at length yesterday with @cujojp, @leemunroe, and myself.  We didn't necessarily reach a unanimous consensus. 

My concerns with `.message-{type} > * { color: inherit; }` were (1) it's a pretty opinionated/strict rule to throw at people and (2) it is likely to have undesirable impact on things like buttons.

So, given the many "what about this?" scenarios, it seemed like a class might be the better route, though more work for the person using the `.message` object.

I like your idea around #2, but that might be better for a separate PR.

**Comment by leemunroe** [comment]
I gave this feedback offline already but I concur with @jfurrow here. Having to rely on developers remembering to add `message-type-style` to all children sounds crazy to me. Both those suggested options sound better.

**Comment by jfurrow** [comment]
I did a little bit of testing and both of my suggestions are going to require a bit of a refactor due to the specificity of nested elements (list items, description list children, etc), but I do think option 2 is a better approach and the refactor investment would be worth it (and save us from future refactors). If we can rely on text color coming from the `body` tag 99% of the time, then all overrides would be really painless.

Another question, do you think bullet points should have the same color as the text? It looks a little weird to me:

**Comment by ashenden** [comment]
@jfurrow +1 on the bullets. and +1 on `p` set to inherit from `body`.  Trying to think if there would be any negative implications of that.

**Comment by ashenden** [comment]
@jfurrow followed through on the bullet color fix. I've also opened another PR for the body<>p change discussed above (see: https://github.com/mesosphere/cnvs/pull/97).

**Pull request merged**
