### PR TITLE
Update comments

### PR DESCRIPTION
**Pull request by jfurrow**
@ashenden In DC/OS UI we also removed the filenames from the heading of each of the LESS files. Do you want to do that here as well?

### CODE REVIEW

**Comment by ashenden** [comment]
Yes.  Please

**Comment by jfurrow** [comment]
@ashenden Done!

**Comment by ashenden** [comment]
@jfurrow can you also adjust the spacing around braces/properties to fall inline with the linting rules, and in a separate branch, add the linting rules so I can go through and begin resolving issues against the linting rules?

**Comment by jfurrow** [comment]
@ashenden Definitely. I plan on addressing the lint fixes in a separate PR, are you cool with that?

**Comment by ashenden** [comment]
👍

**Pull request merged**
