### PR TITLE
Form control feedback

### PR DESCRIPTION
**Pull request by leemunroe**
* Introducing a feedback element for form components that can be used for error (or success) messaging. This is in addition to help text.
* Restyling the validation states of inputs so that the input and feedback are the only highlighted elements.

image

@ashenden @jfurrow

### CODE REVIEW

**Comment by ashenden** [comment]
Thanks.  On quick review, here are some requested changes:
* For the new `.form-control-feedback` component, they should be more than just the 1 or 2 styles they modify (https://cl.ly/4438213d1Y2W).  As these are inherently type elements, they should have all the same variables available to the user to define that they’d have for any other type element.  I’d suggest copying all the variables and styles from the `.lead` type style (https://cl.ly/2s3x273L1A1R and https://cl.ly/2l110o2n3H1B) and then find/replace “lead” with with `.form-control-feedback`.  I only suggesting using `.lead` over `.small`, because find/replace on “small” will also replace the word small in `screen-small` which you don’t want.
* Following the step above, then you can assume null for pretty much all variables, except those you intend to force as defaults for `.form-control-feedback`.
* For both the `.form-control-feedback-error` and `.form-control-feedback-success` style variants, you’d duplicate all the vars and styles you have for the default `.form-control-feedback` element, and only override/change the values you want impacted (e.g. color) all other vars would be `null` and thus ignored on build, but still available to CNVS user to change if they so desired.  This should be a quick find/replace.
* For both the `.form-control-feedback-error` and `.form-control-feedback-success` style variants, you’d want to define the selector as `.form-control-feedback-error, .form-group.form-group-error .form-control-feedback` — similar to the approach we use for `.form-control-error`.

Happy to run through all of this with you in person if you are hung up on any of the points above.

**Comment by leemunroe** [comment]
@ashenden Please review

**Comment by ashenden** [comment]
@leemunroe pushed a handful of updates.  Please review and if all is good, rebase onto `develop` and then merge into `develop` here.

What was changed:
* Updated `.form-control-feedback` variables to inherit from `.small` vars.
* Added top margin to `.form-control-feedback` equivalent to 50% of the margin-bottom applied to `label`s.
* Added additional type style vars for `.form-control-success` and `.form-control-danger` (i.e. ".inverse", ".emphasis", etc...)
* Renamed `.form-control-error` to `.form-control-danger` (to mirror bootstrap names)
* Updated documentation accordingly.
* Rewrote Help Text in form docs to be specific to `.form-control-feedback`

**Comment by ashenden** [comment]
cc/ @jfurrow heads up, we have a new component called `.form-control-feedback` that we'll want to use in DC/OS for all the text feedback that sits below input fields.

**Comment by jfurrow** [comment]
@ashenden Thanks for the heads up! I'll create a JIRA to track this.

**Pull request merged**
