### PR TITLE
Introduce .badge-info badge style

### PR DESCRIPTION
**Pull request by wavesoft**
This PR introduces a new `.badge-info` badge style

image

### CODE REVIEW

**Comment by jfurrow** [comment]
@wavesoft This PR is missing the `components/badges/styles/badge-info` stylesheets :)

**Comment by wavesoft** [comment]
Damn. For some reason I thought the unstaged files was the cached files created with `npm run dist`. Sorry!

**Comment by jfurrow** [comment]
No problem! LGTM 🚢

**Comment by ashenden** [comment]
Yes! We have a new committer!

**Pull request merged**
