### PR TITLE
Structural changes to Canvas repo to support automated builds and docs

### PR DESCRIPTION
**Pull request by ashenden**
@rcorral @mlunoe @jfurrow following through on the work made during the Hackathon in Tulum, I've further improved the canvas repo structure.  We now have included docs, separated source, and a robust Gulp file supporting a number of useful commands for building, serving, and reading for gh-pages (see README).

Before I merge this into `master` and upgrade on npm from `0.2.1` to `0.2.2` I wanted to get your eyes on it make sure there are no major issues you can see.  One thing I was unsure about how to accomplish was making it so that what is published and available via `npm install canvas-ui` is just the contents of the `styles` directory -- not all the supporting docs.  Maybe this is a non-issue?  Thoughts?

### CODE REVIEW

**Comment by rcorral** [comment]
there's some merge conflicts, could you rebase?

**Comment by rcorral** [comment]
what is the main thing I should be reviewing, this PR is very difficult for me to wrap my head around.

**Comment by rcorral** [comment]
@ashenden to only include the required files that you need on `npm install ...` see the [`file`](https://docs.npmjs.com/files/package.json#files) directive for package.json.

**Comment by ashenden** [comment]
@rcorral rebased f`master` onto this branch.  TBH, I really don't follow what rebase is.  Seems to always give me a fuck ton of conflicts I have to sort through.  Either way, it's compiling for me and looks right.

I'm mostly interested in your eyes on this in terms of whether you see any conflicts with your existing workflow.  As long as we can set the contents of the `/styles` directory to be what is published to NPM then we should theoretically be good to go.

**Pull request merged**
