### PR TITLE
Improve form field contrast

### PR DESCRIPTION
**Pull request by jfurrow**
This PR is meant to improve the contrast of form fields. These changes were made with the art direction of @leemunroe :)

Examples:

### CODE REVIEW

**Comment by ashenden** [comment]
@leemunroe @jfurrow this all looks great.  Nice color choices.  However, we missed updating the inverse styling for these components (https://cl.ly/0m0O1P3B0b1G).

**Comment by ngehani** [comment]
Has anyone tried this on a large monitor like the one in the observatory of one of the big screens?

**Comment by jfurrow** [comment]
@ashenden Good catch, I thought Lee and I caught that but apparently not. It's been addressed:

**Comment by ngehani** [comment]
Ooh! - Does that mean the dark theme is easily achievable? :-)

**Comment by ashenden** [comment]
@ngehani we've had this capability all along.  The problem isn't whether our stylesheet supports inverse styling, it's the investment needed in React to go through and hook up all the necessary flags on each/every component to tell those components to invoke the inverse version of themselves. It would like take a single FE engineer 1-2 weeks to do this and QA it.

**Comment by jfurrow** [comment]
@ngehani Not "easy" because the UI would have to add the class `inverse` to thousands of elements in the DC/OS codebase.

Ideally, if we are to introduce a dark theme option, we would apply this class at the root of the tree (e.g. on the `body` tag), but that's not currently possible.

**Comment by ashenden** [comment]
In short, investment needs to be either made on the stylesheet or react. Both would take a chunk of time to do right.

**Review by ashenden — APPROVED** [review]
Changes look great. Inverse looks great as well.  Ship it!

**Pull request merged**
