### PR TITLE
Container width support

### PR DESCRIPTION
**Pull request by ashenden**
Name says it all.  Added in `.prop-variant()` check for `container` width prop.

### CODE REVIEW

**Comment by jfurrow** [comment]
Is the whitespace removal intentional?

**Comment by ashenden** [comment]
No clue. On build that removal happened. Assumed it had something to do with the comment clean up you did a while back.

**Comment by jfurrow** [comment]
Ahh yeah that could be it, I didn't commit anything in the `dist` directory because I didn't realize they were being committed as well.

**Comment by jfurrow** [comment]
:ship:!

**Pull request merged**
