### PR TITLE
Add license

### LINKED ISSUE #3: License
Quick side note:
This repository is public.
I think it needs a license file.

### PR DESCRIPTION
**Pull request by philipnrmn**
Fixes #3

### CODE REVIEW

**Comment by mlunoe** [comment]
We should add the license property to the package.json too

**Comment by philipnrmn** [comment]
Good point, thanks.

**Comment by mlunoe** [comment]
@nklovejoy To this project: Canvas. The styles library that we are using for styling (most of) our frontend projects in Mesosphere.

**Comment by mlunoe** [comment]
@nklovejoy Can we merge this guy?

**Comment by nklovejoy** [comment]
ASL2.0 is what we use.  So if you're got sign-off from Tal to make it open
source in the first place, go for it.

**Comment by philipnrmn** [comment]
Thanks @nklovejoy

**Comment by ashenden** [comment]
Thanks @philipnrmn for pushing this one through.  Merging in.

**Pull request merged**
